In [4]:
import numpy as np
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [8]:
arr1.dtype

dtype('float64')

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
np.empty((2,3,2))

array([[[  1.08310392e-311,   2.81617418e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   2.46567317e+179]],

       [[  4.96297471e-090,   1.80194427e+185],
        [  6.58977439e-043,   1.00671789e-046],
        [  6.48224659e+170,   4.93432906e+257]]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
arr1.dtype

dtype('float64')

In [14]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [15]:
float_arr=arr.astype(np.float64)#显示转换
float_arr.dtype

dtype('float64')

In [16]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [17]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [18]:
int_array=np.arange(10)
calibers=np.array([.22,.270,.357,.380,44,.50],dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [19]:
#数组和标量之间的计算
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [20]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [21]:
#基本的索引和切片
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5:8]=12
arr#数组切片是原始数组的视图，意味着数据不会被复制

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0][2]
arr2d[0,2]#等价

3

In [24]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
old_values=arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr3d[0]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[1,0]

array([7, 8, 9])

In [28]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr2d[:2]#理解为2前面的，不包含2 

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2d[:2,1:]#1后面的包含1

array([[2, 3],
       [5, 6]])

In [31]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [34]:
from scipy import randn
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [35]:
data

array([[-0.52263329,  0.0541778 , -0.27771002, -0.38420335],
       [-0.23072911, -0.43106612,  0.0861957 , -0.0150373 ],
       [ 1.25616725,  0.69436723, -0.77034172, -0.23824477],
       [ 1.16728281,  0.23881476, -0.27572474, -1.30850427],
       [-0.3238475 , -0.46456155, -2.18000896,  0.85392281],
       [-1.13721627, -0.01717829,  0.70752244, -0.80556152],
       [ 0.21650168,  0.75470153,  1.25387202, -1.86676004]])

In [36]:
names=='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [37]:
data[names=='Bob']#条件否定，可以用！=或者负号

array([[-0.52263329,  0.0541778 , -0.27771002, -0.38420335],
       [ 1.16728281,  0.23881476, -0.27572474, -1.30850427]])

In [38]:
data[names=='Bob',2:]

array([[-0.27771002, -0.38420335],
       [-0.27572474, -1.30850427]])

In [40]:
data[data<0]=0#所有负值设置为0
data

array([[ 0.        ,  0.0541778 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.0861957 ,  0.        ],
       [ 1.25616725,  0.69436723,  0.        ,  0.        ],
       [ 1.16728281,  0.23881476,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.85392281],
       [ 0.        ,  0.        ,  0.70752244,  0.        ],
       [ 0.21650168,  0.75470153,  1.25387202,  0.        ]])

In [42]:
data[names!='Joe']=7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.0861957 ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.70752244,  0.        ],
       [ 0.21650168,  0.75470153,  1.25387202,  0.        ]])

In [43]:
#fancy indexing 花式索引
arr=np.empty((8,4))#未初始化的随机值

In [44]:
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [45]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [47]:
#一次传入多个索引数组
arr=np.arange(32).reshape((8,4))#range返回List，arange返回array
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [48]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [49]:
arr[[1,5,7,2]][:,[0,3,1,2]]#或者使用np.ix_函数，将两个一维数组转换为一个用于选取方形区域的索引器

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [50]:
#数组转置和轴对换
#转置返回源数据的视图，不会进行任何复制操作
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [52]:
np.dot(arr.T,arr)#计算内积
#对于高维数组，transpose需要得到一个由轴编号组成的元祖才能对轴进行转

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [56]:
#通用函数：快速的元素级数组函数
arr=np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [57]:
arr=randn(7)*5
arr

array([-2.39640356,  6.12062161, -3.28248665,  0.3517651 , -5.1456445 ,
       -0.03981962,  0.85748524])

In [58]:
np.modf(arr)#用于浮点数数组的小数和整数部分

(array([-0.39640356,  0.12062161, -0.28248665,  0.3517651 , -0.1456445 ,
        -0.03981962,  0.85748524]), array([-2.,  6., -3.,  0., -5., -0.,  0.]))

In [59]:
#利用数组进行数据处理
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [61]:
import matplotlib.pyplot as plt
z=np.sqrt(xs**2+ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [62]:
plt.imshow(z,cmap=plt.cm.gray);
plt.colorbar()

In [63]:
plt.title("Image plot of $\sqrt{x^2+y^2}$for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2+y^2}$for a grid of values')

In [67]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=[(x if c else y)for x,y,c in zip(xarr,yarr,cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [69]:
result=np.where(cond,xarr,yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [70]:
arr=randn(4,4)
np.where(arr>0,2,-2)

array([[ 2, -2, -2, -2],
       [ 2, -2, -2, -2],
       [ 2, -2, -2, -2],
       [-2,  2,  2, -2]])

In [72]:
#数学和统计方法
arr=np.random.randn(5,4)
arr

array([[ 1.67466148,  0.22252404, -0.06619034, -1.09858468],
       [ 0.90602154,  0.37377973,  0.18180045, -0.4801672 ],
       [ 0.60757587,  1.08123951, -0.43067351,  0.1173298 ],
       [ 0.14659681,  1.18846118,  1.12843237,  0.85850412],
       [ 1.54782354, -0.1547547 , -1.43483203,  0.86524898]])

In [73]:
arr.mean()

0.36173984725334085

In [74]:
np.mean(arr)

0.36173984725334085

In [75]:
arr.mean(axis=1)#按行

array([ 0.18310262,  0.24535863,  0.34386791,  0.83049862,  0.20587145])

In [76]:
arr.sum(0)#按列求和

array([ 4.88267924,  2.71124975, -0.62146306,  0.26233101])

In [77]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr.cumsum(0)#按列累加

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [78]:
arr.cumprod(1)#按行累乘

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [82]:
arr=randn(100)
(arr>0).sum()
np.sum(arr>0)

51

In [83]:
bools=np.array([False,False,True,False])
bools.any()
bools.all()

False

In [85]:
#排序
arr=randn(8)
arr.sort()
arr

array([-1.54423518, -0.29893711,  0.24298875,  0.43480815,  0.43650078,
        0.50783673,  0.52918791,  0.81312245])

In [88]:
arr=randn(5,3)
arr.sort(1)#按行进行排序
arr

array([[-0.16388813, -0.0991729 ,  0.25392787],
       [-0.43566222, -0.08900736,  0.81555169],
       [-0.66814987,  0.03611107,  1.21525256],
       [-0.71139337,  0.29347317,  0.59063485],
       [-1.38920426, -0.50597838,  0.62685875]])

In [89]:
large_arr=randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]#5%分位数

-1.5499871075893084

In [90]:
#唯一化及其他的集合逻辑
#unique返回数组中唯一值且排序后的结果
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [94]:
#np.in1d用于测试一个数组中的值在另一个数组中的成员资格
values=np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])


array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [96]:
#用于数组的文件输入输出
arr=np.arange(10)
np.save('some_array',arr)

In [97]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
#将多个数组保存到一个压缩文件中
np.savez('array_archive.npz',a=arr,b=arr)


In [102]:
#得到一个类似字典的对象
arch=np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
#线性代数
x=np.array([[1.,2.,3.],[4.,5.,6.]])
y=np.array([[6.,23.],[-1,7],[8,9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [105]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [106]:
x.dot(y)#相当于np.dot(x,y)

array([[  28.,   64.],
       [  67.,  181.]])

In [107]:
#inv为逆，qr计算QR分解
from numpy.linalg import inv,qr
X=randn(5,5)
mat=X.T.dot(X)
inv(mat)

array([[ 33.51418383, -10.70263938,  11.39021993, -53.10773157,
         29.84857516],
       [-10.70263938,   3.54061852,  -3.5951326 ,  16.94215003,
         -9.42200573],
       [ 11.39021993,  -3.5951326 ,   3.97052601, -18.09619499,
         10.22755633],
       [-53.10773157,  16.94215003, -18.09619499,  84.75410003,
        -47.70045197],
       [ 29.84857516,  -9.42200573,  10.22755633, -47.70045197,
         27.16361108]])

In [108]:
#矩阵乘法
mat.dot(inv(mat))

array([[  1.00000000e+00,  -1.11022302e-15,  -2.88657986e-15,
         -8.88178420e-15,  -1.86517468e-14],
       [  0.00000000e+00,   1.00000000e+00,  -7.10542736e-15,
         -5.68434189e-14,   0.00000000e+00],
       [ -2.84217094e-14,   8.88178420e-15,   1.00000000e+00,
          7.81597009e-14,  -2.13162821e-14],
       [ -1.42108547e-14,   3.55271368e-15,  -7.10542736e-15,
          1.00000000e+00,  -2.84217094e-14],
       [ -2.84217094e-14,   0.00000000e+00,  -7.10542736e-15,
          5.68434189e-14,   1.00000000e+00]])

In [110]:
q,r=qr(mat)
r

array([[-9.36776444, -9.96491033,  9.87660547, -1.4157106 ,  0.63326231],
       [ 0.        , -9.36233806, -0.16995719,  4.78649609,  5.23363891],
       [ 0.        ,  0.        , -9.2488063 , -1.34996702,  1.11633218],
       [ 0.        ,  0.        ,  0.        , -1.72992204, -3.06864642],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.01562212]])

In [111]:
#随机数生成
samples=np.random.normal(size=(4,4))
samples

array([[-0.59187481,  0.6418602 ,  0.30528417, -1.89857114],
       [-2.02871311, -2.38668986, -0.28613577,  0.53866706],
       [-0.6764655 , -1.2589844 ,  0.02403918,  0.76356376],
       [ 0.32581255, -0.72948701,  1.26536399,  1.46151754]])